### ISSUE TITLE
Session Abort when running mean_stack_thresh

### ISSUE THREAD

**Issue by kuang-da** [rorynolan/autothresholdr#6]
Hi, we recently had an issue when running the following code snippet (with `autothresholdr` 1.3.9 and 1.3.11). May I ask what could get wrong? Any suggestion would be highly appreciated.

```
library('autothresholdr')
path <- "data/GFP_GFP_10msec_image_00240.tif"
img <- ijtiff::read_tif(path, msg = TRUE)
autothresholdr::mean_stack_thresh(img, method="Huang")
```

Error Info
```
17 Nov 2021 23:58:20 [rsession-rstudio] ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) src/cpp/session/SessionMain.cpp:680
```

I also created a [virtual environment](https://github.com/kuang-da/mean-stack-thresh-issue) to reproduce the error if that helps.

Thank you very much!

**Comment by kuang-da** [comment]
![image](https://user-images.githubusercontent.com/18092300/142301243-ffe1f789-b71c-4b9b-b974-06d49bf5763f.png)

**Comment by rorynolan** [comment]
Dear @kuang-da 
You were right. There was an issue with stack thresholding which I have now fixed.
New version is submitted to CRAN but might take a while to be available. 
In the meantime, I recommend installing from GitHub with `devtools::install_github("rorynolan/autothresholdr")`. The new version is `1.3.12` so make sure that's the one you have after installation using `packageVersion("autothresholdr")`.
Thank you for your bug report and for preparing all of the docker stuff to make your example reproducible. It made my life easier when looking for the problem and a fix.
Best,
Rory

**Comment by kuang-da** [comment]
Hi @rorynolan,

Thank you so much for the quick response. I confirm that the `devtools::install_github("rorynolan/autothresholdr")` works on the example I provided earlier. Excellent work! Thanks again.
