### ISSUE TITLE
autothresholdR on Pre-calculated Table

### ISSUE THREAD

**Issue by plhm** [rorynolan/autothresholdr#7]
Hi there Dr. Nolan,

First of all, thanks much for taking this useful piece of software from ImageJ into R. Dr. Nolan, I have used ImageJ along with R to obtain a table of R, G and B counts averaged across a couple hundred figures. My idea is to run AutoThreshold with ImageJ's default mode to obtain a 'global' threshold for each of the color channels, and then use this value to threshold each image separately.

My input data would be a simple table with two columns: Column 1 has the 'Value' (from 0 to 255) entries, while column 2 has the counts for each value. Looking through your code, it appears to this would be a similar format to what you are using to implement your approach after some initial steps of data processing. I'd like to suggest that you a also make available function in your package that would take a table-like input, and perform the auto-threshold analysis. If you don't feel like making this a function on its own, I'd very much appreciate if you could provide me with some suggestions on how to achieve my goal, and I'd gladly cite your package and Acknowledge you in the mansucript, regardless.

Thank you very much for your time, Dr. Nolan.

Best,

P

**Comment by rorynolan** [comment]
Dear @plhm 
This is a good idea and I will work on implementing it in the coming days. Hopefully I can have something for you this week.
Thank you for the idea and I am glad that the software is useful for you.
Rory

**Comment by plhm** [comment]
Hi Nolan,

Thanks much. I'm looking forward to it. Please let me know if I can provide
any additional information or be of any use.

Best,

P

**Comment by rorynolan** [comment]
Hi @plhm 
I have a new version 1.4.0 on GitHub now featuring what you requested.
See https://rorynolan.github.io/autothresholdr/articles/finding-thresholds.html#using-a-frequency-table for how to do it.
Please test-drive it and tell me what you think. When it is settled, I will release to CRAN.
Thanks,
Rory

**Comment by rorynolan** [comment]
Dear @plhm 
I will release to CRAN in the next few days.
Rory

**Comment by plhm** [comment]
Hi there Rory,

Happy new year. I just tried the updated version of the code. Worked like a
charm. I appreciate you taking the time to make this available.

Best,

P

**Comment by rorynolan** [comment]
It's on CRAN now! 
Thanks for a great suggestion.
