### ISSUE TITLE
Assertion on 'int_arr' failed

### ISSUE THREAD

**Issue by joqb** [rorynolan/autothresholdr#8]
Hello,

I would like to use this package to threshold images but I am getting an error.
`> ndvi <-  ijtiff::read_tif("Z:/MAGIC_Resist/HAL2019/B2_WW_SW/004.Banden/MCAW_ALN/NDVI/H19_B2_MCAW_ALN_2019-05-10_NDVI.tif")
Reading H19_B2_MCAW_ALN_2019-05-10_NDVI.tif: a 32-bit,
6203x6228 pixel image of floating point type. Reading 1
channel and 1 frame . . . Done.
There were 11 warnings (use warnings() to see them)
mask <- auto_thresh_mask(ndvi, "Otsu" ,ignore_black = TRUE, ignore_white = TRUE, ignore_na = TRUE)
`
The error is 
Assertion on 'int_arr' failed: Must be of type 'integerish', but element 12868 is not close to an integer.

From there I can see that my images don't have the proper format, how do I convert a floating type image to an integer type?

Best regards
Jonathan

**Comment by rorynolan** [comment]
Hi Jonathan,
Can you send me the image so I can play with it?
Perhaps you can attach it here?
Best,
Rory

**Comment by joqb** [comment]
Hi Rory,

thanks for the quick reply, I was not able to attach the image on the GitHub (probably too large) so I try to share it via this link

[https://outlook-2.cdn.office.net/assets/mail/file-icon/png/zip_16x16.png]H19_B2_MCAW_ALN_2019-05-10_NDVI.zip<https://1drv.ms/u/s!AglPblU2Jz9nhQL0kzgU2MBZ59i3>

I hope this works.

For information, I have UAV images from wheat fields. The images (multichannel camera, thermal, and RG) were taken across the season.
For the moment, I am using a NDVI with a fixed threshold value to mask soil pixels. However, one thing that I realized is that at the end of the season, using this method the plants are being masked.
I was hoping that your package could do something a little more sensitive, or maybe you have an idea how I can solve this issue.

Cheers
Joanthan

--



Dr Jonathan Brassac


Martin Luther University Halle-Wittenberg (Germany)
Institute of Agricultural and Nutritional Sciences
https://www.landw.uni-halle.de/prof/plantbreeding/
Tel:  +49-(0)15775701793
________________________________
De : Rory Nolan ***@***.***>
Envoyé : mardi 26 avril 2022 23:06
À : rorynolan/autothresholdr ***@***.***>
Cc : joqb ***@***.***>; Author ***@***.***>
Objet : Re: [rorynolan/autothresholdr] Assertion on 'int_arr' failed (Issue #8)


Hi Jonathan,
Can you send me the image so I can play with it?
Perhaps you can attach it here?
Best,
Rory

**Comment by rorynolan** [comment]
Hi Jonathan,
Sorry for the late reply. 
The image is indeed in floating point. Minimum value is -0.5657375, maximum is 1.0. 
This makes it difficult to threshold. We can get around it and I will help you but first I'd like to see if we can get it in better format. What device did you take the image on?
Best,
Rory

**Comment by joqb** [comment]
Hi Rory,

the raw images were captured on a Tetracam MACAW multispectral camera and then assembled into Orthomosaics with Agisoft Metashape Professional (1.5).

Best regards,
Jonathan

Von: Rory ***@***.***>
Gesendet: Donnerstag, 5. Mai 2022 18:40
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [rorynolan/autothresholdr] Assertion on 'int_arr' failed (Issue #8)


Hi Jonathan,
Sorry for the late reply.
The image is indeed in floating point. Minimum value is -0.5657375, maximum is 1.0.
This makes it difficult to threshold. We can get around it and I will help you but first I'd like to see if we can get it in better format. What device did you take the image on?
Best,
Rory

**Comment by rorynolan** [comment]
It's probably the mosaic construction that's the problem. Do you have a
choice of format for the mosaic output file? Or is it TIFF only? And do you
still have the original files from which the mosaic was made? What format
are they?

**Comment by joqb** [comment]
The orthomosaics are exported in TIFF with LZW compression. Other formats/compressions are possible (JPEG, Packbits, and Deflate).
I still have the original files and they are TIFF as well.
But regenerating the Orthomosaics would not be an option in the few months I am still on the job (ca. 200 orthomosaics).

--



Dr Jonathan Brassac


Martin Luther University Halle-Wittenberg (Germany)
Institute of Agricultural and Nutritional Sciences
https://www.landw.uni-halle.de/prof/plantbreeding/
Tel:  +49-(0)15775701793
________________________________
De : Rory Nolan ***@***.***>
Envoyé : mercredi 11 mai 2022 15:01
À : rorynolan/autothresholdr ***@***.***>
Cc : joqb ***@***.***>; Author ***@***.***>
Objet : Re: [rorynolan/autothresholdr] Assertion on 'int_arr' failed (Issue #8)


It's probably the mosaic construction that's the problem. Do you have a
choice of format for the mosaic output file? Or is it TIFF only? And do you
still have the original files from which the mosaic was made? What format
are they?

**Comment by rorynolan** [comment]
What are the other export formats? Can you do plain PNG or JPG (as you
probably know, plain JPG and TIFF with JPG compression are different).

**Comment by joqb** [comment]
From the Agisoft Metashape user manual: "Multispectral orthomosaic export is supported in GeoTIFF format only."
So plain PNG or JPG is not an option.

--



Dr Jonathan Brassac


Martin Luther University Halle-Wittenberg (Germany)
Institute of Agricultural and Nutritional Sciences
https://www.landw.uni-halle.de/prof/plantbreeding/
Tel:  +49-(0)15775701793
________________________________
De : Rory Nolan ***@***.***>
Envoyé : mercredi 11 mai 2022 16:14
À : rorynolan/autothresholdr ***@***.***>
Cc : joqb ***@***.***>; Author ***@***.***>
Objet : Re: [rorynolan/autothresholdr] Assertion on 'int_arr' failed (Issue #8)


What are the other export formats? Can you do plain PNG or JPG (as you
probably know, plain JPG and TIFF with JPG compression are different).

**Comment by rorynolan** [comment]
Hi Jonathan,
It seems you don't have ability to change the format on your end then.
The solution is to convert your image to 16-bit integer using BBmisc range normalization and rounding. Once it is 16-bit integer, you can get the mask.
I give an example here with the output mask.

``` r
library(ijtiff)
library(autothresholdr)

orig_img <- read_tif(
  "~/Downloads/H19_B2_MCAW_ALN_2019-05-10_NDVI.tif"
)
#> Reading H19_B2_MCAW_ALN_2019-05-10_NDVI.tif: a 32-bit,
#> 6203x6228 pixel image of floating point type. Reading 1
#> channel and 1 frame . . .
#>  Done.

img_vector <- as.vector(orig_img)

img_vector_16bit <- round(
  BBmisc::normalize(img_vector, method = "range", range = c(0, 2^16 - 1))
)

img_16bit <- array(img_vector_16bit, dim = dim(orig_img))

mask <- auto_thresh_mask(img_16bit, "Otsu", 
                         ignore_black = TRUE, ignore_white = TRUE, 
                         ignore_na = TRUE)
```

<sup>Created on 2022-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

![joqb-mask](https://user-images.githubusercontent.com/20400852/168130693-76ec6d0a-0f50-4a43-bbdd-b03e1d026a2e.png)
