### ISSUE TITLE
auto_thresh function for codex data

### ISSUE THREAD

**Issue by annamath** [rorynolan/autothresholdr#9]
Hi, 

I am working on a CODEX dataset containing immunofluorescence intensities of segmented single cells. 

I tried to apply the autothresholdr::auto_thresh function in order to obtain appropriate thresholds for marker positivity. 
I understand that the function’s input is a non-negative integer vector, however we are working with  intensity values ranging from around -1 to 100 also containing decimal points. Rounding the intensities with as.integer before running the thresholding would possibly skew the results. 

Do you have any idea of how to tackle this problem? 
Thanks :)

**Comment by rorynolan** [comment]
Dear @annamath 
Is is possible for you to share a sample of the data with me?
Thanks,
Rory

**Comment by annamath** [comment]
Hello Rory! 

In the csv attached you can find 2 example markers, each row represents a single cell. 
[20220728_Codex_Example_autothres.csv](https://github.com/rorynolan/autothresholdr/files/9206070/20220728_Codex_Example_autothres.csv)
Thank you for your answer and your time :) 

Anna

**Comment by rorynolan** [comment]
Your only hope is to convert to integers. You're right that simple rounding with `as.integer()` will lose too much precision. A good option is to scale your data into the 16-bit integer range and then round. That way you keep the precision of around 65000 bins instead of 100 or so. I give an example of how to do this with your data.

``` r
codex <- read.csv("~/Downloads/20220728_Codex_Example_autothres.csv")

get_decimal_thresh <- function(x, method, 
                               ignore_black = FALSE, ignore_white = FALSE,
                               ignore_na = FALSE) {
  int_x <- x |>
    BBmisc::normalize(method = "range", range = c(0, 2 ^ 16 - 1)) |>
    round()
  int_x_thresh <- autothresholdr::auto_thresh(int_x, method = method,
                                              ignore_black = ignore_black,
                                              ignore_white = ignore_white,
                                              ignore_na = ignore_na)
  BBmisc::normalize(c(range(int_x), int_x_thresh), 
                    method = "range", range = range(x))[3]
}

get_decimal_thresh(codex$marker1, "default")
#> [1] 0.700595
get_decimal_thresh(codex$marker1, "triangle")
#> [1] -0.5759267
get_decimal_thresh(codex$marker2, "default")
#> [1] 3.496673
get_decimal_thresh(codex$marker2, "triangle")
#> [1] 0.5519913
```

<sup>Created on 2022-07-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
